# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true
relative_permalinks:
  collections: true

# Setup
title:            Xinyi Dong
tagline:          'Technical Artist'
description:      'Technical Artist'
url:              http://blumenkranz07.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
# gems:                [jekyll-paginate]
# paginate:            5
# paginate_path:       "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/blumenkranz07/blumenkranz07.github.io
